- stat: path=/mnt/etc/localtime
  register: localtime
  tags:
  - chroot

- name: run commands in chroot
  command: "arch-chroot /mnt {{ item }}"
  with_items:
    - ln -s /usr/share/zoneinfo/{{ locale.region }}/{{ locale.city }} /etc/localtime
    - grub-install --target=i386-pc "{{ disk }}"
    - grub-mkconfig -o /boot/grub/grub.cfg
    - mkinitcpio -p linux
    - locale-gen
    - systemctl enable dhcpcd
    - systemctl enable sshd
    - bash -c 'echo "PermitRootLogin prohibit-password" >> /etc/ssh/sshd_config'
  when:
    - chroot.stat.exists
    - localtime.stat.exists == False
  tags:
    - chroot

- name: set root password
  template:
    src: "{{ role_path }}/templates/pwd.sh.tpl"
    dest: /pwd.sh
    mode: 0755

- command: "/pwd.sh"
  when: chroot.stat.exists
  tags:
    - chroot

- file:
    path: /pwd.sh
    state: absent
  tags:
    - chroot

- name: "generate keypair"
  local_action: command ssh-keygen -b 4096 -t rsa -f "{{ playbook_dir }}/{{ ssh.keyfile }}" -q -N "{{ ssh.passphrase }}" creates="{{ playbook_dir }}/{{ ssh.keyfile }}.pub"
  tags:
    chroot

- file:
    path: /mnt/root/.ssh
    mode: 0700
    state: directory
  when: chroot.stat.exists
  tags:
    chroot

- copy:
    src: "{{ playbook_dir }}/{{ ssh.keyfile }}.pub"
    dest: /mnt/root/.ssh/authorized_keys
    mode: 0600
  when:
    - chroot.stat.exists
  tags:
    - chroot
