- stat: path=/mnt/boot/i386-pc
  register: grub

- name: install kernel, grub and generate locale in chroot
  command: "arch-chroot /mnt {{ item }}"
  with_items:
    - mkinitcpio -p linux
    - grub-install --target=i386-pc "{{ disk }}"
    - grub-mkconfig -o /boot/grub/grub.cfg
    - locale-gen
  when:
    - grub.stat.exists == False

- name: configure timezone
  file:
    src: ../usr/share/zoneinfo/{{ timezone.region }}/{{ timezone.city }}
    dest: /mnt/etc/localtime

- name: enable dhcpcd
  command: arch-chroot /mnt systemctl enable dhcpcd creates="/mnt/etc/system/multi-user.target.wants/dhcpcd.service"

- name: enable sshd
  command: arch-chroot /mnt systemctl enable sshd creates="/mnt/etc/system/multi-user.target.wants/sshd.service"

- name: enable keylogin for root
  replace:
    dest: /mnt/etc/ssh/sshd_config
    regexp: '(#PermitRootLogin\s+prohibit-password)'
    replace: 'PermitRootLogin prohibit-password'

- name: set root password
  template:
    src: "{{ role_path }}/templates/pwd.sh.tpl"
    dest: /pwd.sh
    mode: 0755

- command: "/pwd.sh"

- file:
    path: /pwd.sh
    state: absent

- name: "generate keypair"
  local_action: command ssh-keygen -b 4096 -t rsa -f "{{ playbook_dir }}/{{ ssh.keyfile }}" -q -N "{{ ssh.passphrase }}" creates="{{ playbook_dir }}/{{ ssh.keyfile }}.pub"

- file:
    path: /mnt/root/.ssh
    mode: 0700
    state: directory

- copy:
    src: "{{ playbook_dir }}/{{ ssh.keyfile }}.pub"
    dest: /mnt/root/.ssh/authorized_keys
    mode: 0600
