# Basic configuration
- name: generate fstab
  template:
    src: "{{ role_path }}/templates/fstab.tpl"
    dest: /mnt/etc/fstab

- name: copy mkinitcpio.conf file
  copy:
    src: "{{ role_path }}/files/mkinitcpio.conf"
    dest: /mnt/etc/mkinitcpio.conf

- name: enable locales
  template:
    src: "{{ role_path }}/templates/locale.gen.tpl"
    dest: /mnt/etc/locale.gen

- name: configure locale.conf file
  template:
    src: "{{ role_path }}/templates/locale.conf.tpl"
    dest: /mnt/etc/locale.conf

- name: set hostname
  template:
    src: "{{ role_path }}/templates/hostname.tpl"
    dest: /mnt/etc/hostname

- name: configure hostfile
  template:
    src: "{{ role_path }}/templates/hosts.tpl"
    dest: /mnt/etc/hosts
