# Basic configuration
- name: generate fstab
  template:
    src: "{{ role_path }}/templates/fstab.tpl"
    dest: /mnt/etc/fstab
    mode: 0644

- name: copy mkinitcpio.conf file
  copy:
    src: "{{ role_path }}/files/mkinitcpio.conf"
    dest: /mnt/etc/mkinitcpio.conf

- name: copy locale.conf file
  copy:
    src: "{{ role_path }}/files/locale.conf"
    dest: /mnt/etc/locale.conf

- name: copy locale.conf file
  copy:
    src: "{{ role_path }}/files/locale.conf"
    dest: /mnt/etc/locale.conf

- name: configure hostfile
  template:
    src: "{{ role_path }}/templates/hostname.tpl"
    dest: /mnt/etc/hostname
    mode: 0644

- name: configure hostfile
  template:
    src: "{{ role_path }}/templates/hosts.tpl"
    dest: /mnt/etc/hosts
    mode: 0644
