---
# tasks file for bootstrap
- include: partitioning.yml
  tags:
  - disk

- stat: path=/tmp/formating_finished
  register: formating
  tags:
  - filesystem

- include: formating.yml
  when: formating.stat.exists == False
  tags:
  - filesystem

- file:
    path: /tmp/formating_finished
    state: touch
  tags:
  - filesystem

- stat: path=/mnt/boot
  register: mounted
  tags:
  - mount
  - install
  - configure

- name: mount filesystems
  command: "{{ item }}"
  when: mounted.stat.exists == False
  with_items:
    - mount "{{ lvm.vg.system.lv.root.dev }}" /mnt
    - mkdir -p /mnt/boot
    - mkdir -p /mnt/home
    - mount "{{ part.2.dev }}" /mnt/boot
  tags:
    - mount

- name: check if installed
  stat: path=/mnt/bin/bash
  register: packages
  tags:
    - install
    - configure

- name: install base packages
  command: pacstrap /mnt base f2fs-tools xfsprogs util-linux grub openssh python2
  when: packages.stat.exists == False
  tags:
    - install

- stat: path=/tmp/configuration_finished
  register: config
  tags:
  - configure

- include: configure.yml
  when: config.stat.exists == False
  tags:
  - configure

- file:
    path: /tmp/configuration_finished
    state: touch
  tags:
  - configure

- stat: path=/mnt/etc
  register: chroot
  tags:
    - chroot

- include: chroot.yml
  when: chroot.stat.exists
  tags:
  - configure

- name: unmount filesystems
  command: "umount {{ item }}"
  with_items:
    - /mnt/boot
    - /mnt
  when: chroot.stat.exists
  tags:
    - chroot
